### ISSUE TITLE
Update on Readme File

### ISSUE THREAD

**Issue by sourabhsingh282** [NISYSLAB/Emory-BMI-GSoC#3]
This is the similar project used which also build by IBM (auto AI in IBM Watson studio), I think you  should refers this YouTube link 
https://www.youtube.com/watch?v=EDQ0AWcUBnE
In order to give an idea to new contributors  that what kind of problem we are trying to solve here  instead of telling them it is like simulator in matlab  I think it will be great start
we can update in the read me section of project : TensorFlow-GUI: A Graphical User Interface for Tensorflow

**Comment by pradeeban** [comment]
Hi,
Thanks for your thoughts.

The GSoC page is intentionally left without too many specifics so that the students can polish and build their own idea. Please include your ideas and interpretations in your proposal.

As we are reaching the end of the application period, we are no longer making edits to the project ideas page.

**Comment by huntermarchi** [comment]
I am writing to express my keen interest in contributing to the Biomedical Informatics Department's projects as part of the Google Summer of Code program. The opportunity to work on innovative tools and technologies aimed at advancing healthcare aligns perfectly with my academic background and passion for using technology to make a positive impact on society.

I am particularly drawn to the multidisciplinary nature of the projects undertaken by your department, which span areas such as cancer research, organ transplant, HIV, and medical imaging. My experience makes me confident in my ability to contribute effectively to the development of open-source solutions that address real-world challenges in healthcare.

I am excited about the prospect of collaborating with experienced mentors and fellow contributors to create impactful software that can improve patient care and medical research outcomes. Please consider my application for participation in the Google Summer of Code program, and I look forward to the opportunity to contribute to your esteemed organization.
